name: SGDForRegression
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - prettytable
  - networkx
  - pandas
  - scikit-learn
  - seaborn
